version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pin@12345
      MYSQL_DATABASE: product_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecom-net

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pin@12345
    networks:
      - ecom-net

volumes:
  mysql_data:

networks:
  ecom-net:

